@startuml
!theme plain
top to bottom direction
skinparam linetype ortho

class Person {
   id:  Long
   first_name:  String
   second_name:  String
   last_name:  String
   title:  String
   lead:  String
   original_ais_person_id:  Long
   photo:  String
   url:  String
}

class Commission {
   id:  Long
   description:  String
   short_title:  String
   title:  String
   type:  String
   url_website:  String
}

class CommissionPosition {
   person_id:  Long
   commission_id:  Long
   position_text:  String
   position_type:  String
   regions_title:  String
}

'main .(delete cascade). secondary
Person                "1" -[#000000,plain]-> "0..*"  CommissionPosition
Commission            "1" -[#000000,plain]-> "0..*"  CommissionPosition

class Region {
   id:  String
   title:  String
}

class RegionToCommissionPosition {
    region_id:  String
    commission_position_id:  Long
}

'main .(delete cascade). secondary
Region               "1" -[#000000,plain]-> "0..*"  RegionToCommissionPosition
CommissionPosition   "1" -[#000000,plain]-> "0..*"  RegionToCommissionPosition

class Convocation {
   id:  Long
   deputies_url:  String
   num_genitive:  String
}
class Fraction {
   id:  Long
   description:  String
   short_title:  String
   title:  String
   type:  String
   url_website:  String
}
class FractionPosition {
   convocation_id:  Long
   fraction_id:  Long
   person_id:  Long
   actual:  boolean
   place_in_hall_column:  Integer
   place_in_hall_column:  Integer
}

Convocation           "1" -[#000000,plain]-> "0..*"  FractionPosition
Fraction              "1" -[#000000,plain]-> "0..*"  FractionPosition
Person                "1" -[#000000,plain]-> "0..*"  FractionPosition

class RegionToFractionPosition {
    region_id:  String
    fraction_position_id:  Long
}

Region               "1" -[#000000,plain]-> "0..*"  RegionToFractionPosition
FractionPosition     "1" -[#000000,plain]-> "0..*"  RegionToFractionPosition

class Country {
   id:  String
   title:  String
   url:  String
}
class CountryToCountry {
   from_id:  String
   to_id:  String
}

'from_id
Country               "1" -[#000000,plain]-> "0..*"  CountryToCountry
'to_id
Country               "1" -[#000000,plain]-> "0..*"  CountryToCountry

class IntCommission {
   id:  Long
   lead:  String
   title:  String
   url_website:  String
}

class CountryToIntCommission {
   country_id:  String
   int_commission_id:  Long
}

Country               "1" -[#000000,plain]-> "0..*"  CountryToIntCommission
IntCommission         "1" -[#000000,plain]-> "0..*"  CountryToIntCommission

class IntCommissionPosition {
   id:  Long
   title:  String
}
class PersonToIntCommissionPosition {
   person_id:  Long
   int_commission_position_id:  Long
}

Person                "1" -[#000000,plain]-> "0..*"  PersonToIntCommissionPosition
IntCommissionPosition "1" -[#000000,plain]-> "0..*"  PersonToIntCommissionPosition

class IntGroup {
   id:  Long
   lead:  String
   title:  String
   url_website:  String
}
class CountryToIntGroup {
   country_id:  String
   int_group_id:  Long
}

Country               "1" -[#000000,plain]-> "0..*"  CountryToIntGroup
IntGroup              "1" -[#000000,plain]-> "0..*"  CountryToIntGroup

class IntGroupPosition {
   id:  Long
   int_group_id:  Long
   title:  String
}

IntGroup              "1" -[#000000,plain]-> "0..*"  IntGroupPosition

class PersonToIntGroupPosition {
   person_id:  Long
   int_group_position_id:  Long
}

Person                "1" -[#000000,plain]-> "0..*"  PersonToIntGroupPosition
IntGroupPosition      "1" -[#000000,plain]-> "0..*"  PersonToIntGroupPosition

class StaffOrg {
   org:  long
   orgTitle:  String
}

class PersonToStaffOrg {
   person_id:  Long
   staff_org_id:  Long
}

Person                "1" -[#000000,plain]-> "0..*"  PersonToStaffOrg
StaffOrg              "1" -[#000000,plain]-> "0..*"  PersonToStaffOrg

@enduml
